context:
  version: "10.0"

recipe:
  name: slang-verilog-packages
  version: ${{ version }}

source:
  url: https://github.com/MikePopoloski/slang/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2032cd8bb1c1218060abcc2bd27c77e98cc1880741a589bf19d41663c563c9d0
  patches:
    - 0001-fix-get-target-property.patch

build:
  number: 0

outputs:
  - package:
      name: slang-verilog
    build:
      number: 0
      script:
        - if: unix
          then: build.sh
        - if: win
          then: build.bat
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake >=3.20
        - ninja
        - python
      host:
        - fmt >=12.1
        - if: not win
          then:
            - mimalloc >=2.2
        - libboost-devel >=1.87
      run:
        - fmt >=12.1
      ignore_run_exports:
        by_name:
          - libboost-devel
    tests:
      - script:
          - if: unix
            then:
              - test -f $PREFIX/lib/libsvlang$SHLIB_EXT
              - test -f $PREFIX/bin/slang
              - slang --version
          - if: win
            then:
              - if not exist %LIBRARY_LIB%\svlang.lib exit 1
              - slang --version

  - package:
      name: slang-systemverilog
    build:
      number: 0
      noarch: generic
      script: "echo 'alias package'"
    requirements:
      run:
        - slang-verilog ==${{ version }}
    tests:
      - script:
          - slang --version

  - package:
      name: slang-sv
    build:
      number: 0
      noarch: generic
      script: "echo 'alias package'"
    requirements:
      run:
        - slang-verilog ==${{ version }}
    tests:
      - script:
          - slang --version

  - package:
      name: svlang
    build:
      number: 0
      noarch: generic
      script: "echo 'alias package'"
    requirements:
      run:
        - slang-verilog ==${{ version }}
    tests:
      - script:
          - slang --version

about:
  homepage: https://sv-lang.com/
  summary: SystemVerilog compiler and language services
  description: |
    slang is a software library that provides various components needed to
    lexically analyze, parse, type check, and elaborate SystemVerilog code.
    It comes with an executable tool that can compile and lint
    SystemVerilog and is also usable as a library to power other tools.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/MikePopoloski/slang
  documentation: https://sv-lang.com/user-manual.html

extra:
  feedstock-name: slang-verilog
  recipe-maintainers:
    - timkpaine
